export { default as LandingPageApp } from './landing-page';
export { default as ClientApp } from './client';
export { default as AdminApp } from './admin';
export { default as AdminProductApp } from './admin-product';
export { default as AdminServiceApp } from './admin-service';
export { default as ClientProductApp } from './client-product';
export { default as ClientPetsApp } from './client-pets';
export { default as ClientDetailsApp } from './client-details';
export { default as AdminDetailsApp } from './admin-details';
